### ISSUE TITLE
Crash: Shift right click expulsion to expulsion 

### ISSUE THREAD

**Issue by ghost** [Drazuam/RunicArcana#2]
Expulsion symbol 1 placed on chest 1, expulsion symbol 2 placed on chest 2. Shift right click enabled option in symbol 1 then right-click symbol 2 causes crash.

**Comment by Drazuam** [comment]
Fixed in Commit [35a9e3b](https://github.com/Drazuam/RunicArcana/commit/35a9e3b9e21221b7aab678aa54a8bc37722a589b)
